### ISSUE TITLE
Formbot example strange domain.yml

### ISSUE THREAD

**Issue by ulf2us** [RasaHQ/rasa-examples#2]
The formbot example seems to have several issues, one of them is why should a number of people should be 'float' and max is 1.0?

num_people:
    type: rasa.shared.core.slots.FloatSlot
    initial_value: null
    auto_fill: false
    influence_conversation: false
    max_value: 1.0
    min_value: 0.0

**Comment by koaning** [comment]
I'll have a look. It should be said though that I copied these examples in from the `/examples` folder in the main rasa project [here](https://github.com/RasaHQ/rasa/blob/main/examples/formbot/domain.yml#L28-L30). This repo is bound to change once we hit 3.x.

**Comment by ulf2us** [comment]
Thank you very much. I figured it out myself, if you change the domain.yml altering the slots section to
  num_people:
    type: rasa.shared.core.slots.TextSlot
and the forms section to
  num_people:
      - entity: number
        intent:
        - inform
        - request_restaurant
        type: from_text

the example is running smooth and fine
